USE DBI_Assignment

CREATE TABLE Territory(
	TerID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TerName NVARCHAR(30) NOT NULL
)
CREATE TABLE Student(
	sID VARCHAR(25) NOT NULL PRIMARY KEY,
	TerID INT NOT NULL FOREIGN KEY REFERENCES Territory(TerID),
	sFirstName NVARCHAR(30) NOT NULL,
	sLastName NVARCHAR(30) NOT NULL,
	Dob DATE NOT NULL,
	Sex BIT NOT NULL,
	Major VARCHAR(55) NOT NULL,
	mail VARCHAR(70) NOT NULL,
	[Image] NVARCHAR(255) NOT NULL,
)

CREATE TABLE Lecture(
	lID VARCHAR(25) NOT NULL PRIMARY KEY,
	TerID INT NOT NULL FOREIGN KEY REFERENCES Territory(TerID),
	lFirstName NVARCHAR(30) NOT NULL,
	lLastName NVARCHAR(30) NOT NULL,
	Dob DATE,
	Sex BIT NOT NULL,
	WorkedSince DATE NOT NULL,
	mail VARCHAR(70) NOT NULL,
)
CREATE TABLE Course(
	cID VARCHAR(15) NOT NULL PRIMARY KEY,
	cName VARCHAR(70) NOT NULL,
	[Number of sessions] INT NOT NULL,
	Department VARCHAR(70) NOT NULL,
	Semester VARCHAR(15) NOT NULL,
	[Number of credits] INT NOT NULL,
)

CREATE TABLE StudentGroup(
	gID VARCHAR(15) NOT NULL,
	sID VARCHAR(25) NOT NULL FOREIGN KEY REFERENCES Student(sID),
	cID VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES Course(cID),
	CONSTRAINT pk_StudentID_CourseID_GroupID PRIMARY KEY (gID,sID,cID),
	EnrolledDate DATE NOT NULL,
)
CREATE TABLE Class(
	ClassID VARCHAR(80) NOT NULL PRIMARY KEY,
	lID VARCHAR(25) NOT NULL FOREIGN KEY REFERENCES Lecture(lID),
)
CREATE TABLE [Studied-in](
	ClassID VARCHAR(80) NOT NULL,
	sID VARCHAR(25) NOT NULL ,
	cID VARCHAR(15) NOT NULL ,
	gID VARCHAR(15) NOT NULL,
	[Attendance status] BIT NOT NULL,
	CONSTRAINT PK_ClassID_LectureID_CourseID_GroupID_StudentID PRIMARY KEY (ClassID,sID,cID,gID),
	CONSTRAINT fk_StudentID_CourseID_GroupID FOREIGN KEY (gID,sID,cID) 
	REFERENCES StudentGroup(gID,sID,cID),
	CONSTRAINT fk_ClassID FOREIGN KEY (ClassID) REFERENCES Class(ClassID)
)

CREATE TABLE Work(
	Category VARCHAR(40) NOT NULL PRIMARY KEY,
	cID VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES Course(cID),
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
)

CREATE TABLE Assessment(
	AssessmentID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Category VARCHAR(40) NOT NULL FOREIGN KEY REFERENCES Work(Category),
	[Type] NVARCHAR(15) NOT NULL,
	Part INT NOT NULL,
	[Weight] DECIMAL(5,2) NOT NULL,
	[Completion Criteria] INT NOT NULL,
	[No Question] INT,
)

CREATE TABLE Process(
	sID VARCHAR(25) NOT NULL FOREIGN KEY REFERENCES Student(sID),
	Category VARCHAR(40) NOT NULL FOREIGN KEY REFERENCES Work(Category),
	CONSTRAINT pk_StudentID_Category PRIMARY KEY (sID,Category),
)

CREATE TABLE [Output](
	OutputID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	sID VARCHAR(25) NOT NULL,
	Category VARCHAR(40) NOT NULL,
	CONSTRAINT fk_StudentID_Category FOREIGN KEY (sID,Category) REFERENCES Process(sID,Category),
	SubmisstionStatus BIT NOT NULL,
)

CREATE TABLE Grading(
	lID VARCHAR(25) NOT NULL FOREIGN KEY REFERENCES Lecture(lID),
	OutputID INT NOT NULL FOREIGN KEY REFERENCES [Output](OutputID),
	CONSTRAINT pk_LectureID_OutputID PRIMARY KEY (lID,OutputID),
)

CREATE TABLE Result(
	OutputID INT NOT NULL,
	[Graded by] VARCHAR(25) NOT NULL,
	CONSTRAINT fk_OutputID_Graded_by FOREIGN KEY ([Graded by],OutputID) REFERENCES Grading(lID,OutputID),
	AssessmentID INT NOT NULL FOREIGN KEY REFERENCES Assessment(AssessmentID),
	CONSTRAINT pk_OutputID_Graded_by_AssessmentID PRIMARY KEY (OutputID,[Graded by],AssessmentID),
	[Day of publication] DATE NOT NULL,
	Mark FLOAT,
	[Status] BIT,
)

---BEGIN INSERT 
-- TERRITORY
INSERT INTO Territory(TerName)
VALUES
(N'North'),
(N'South'),
(N'East'),
(N'West')
SELECT * FROM Territory
